# Generated by Django 5.0.1 on 2024-02-10 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('User_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('First_Name', models.CharField(max_length=40)),
                ('Last_Name', models.CharField(max_length=40)),
                ('Phone_Number', models.CharField(max_length=40)),
                ('Email', models.EmailField(max_length=30)),
                ('Password', models.CharField(max_length=15)),
                ('RL_Points', models.IntegerField(default=0, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Flavoring',
            fields=[
                ('Product_Name', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('Product_Description', models.TextField(max_length=400)),
                ('Image', models.ImageField(upload_to='RL_Images/')),
                ('Available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('Product_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('Product_Type', models.CharField(choices=[('CNSM', 'Consumable'), ('ASST', 'Asset'), ('ADVT', 'Advertisement'), ('MISC', 'Miscellaneous')], max_length=15)),
                ('Product_Name', models.CharField(max_length=25)),
                ('Product_Description', models.TextField(max_length=300)),
                ('Price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('Available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemOrder',
            fields=[
                ('Rental_Num', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('Primary', models.CharField(choices=[('R', 'Red'), ('B', 'Blue'), ('G', 'Green'), ('Y', 'Yellow'), ('P', 'Pink'), ('E', 'Grey'), ('W', 'White'), ('K', 'Black')], max_length=15)),
                ('Secondary', models.CharField(blank=True, choices=[('R', 'Red'), ('B', 'Blue'), ('G', 'Green'), ('Y', 'Yellow'), ('P', 'Pink'), ('E', 'Grey'), ('W', 'White'), ('K', 'Black')], default='N/A', max_length=15)),
                ('Cups', models.IntegerField(default=0)),
                ('Rimmer_Paks', models.IntegerField(default=0)),
                ('Salt_Paks', models.IntegerField(default=0)),
                ('Customer', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='RL_App.account')),
            ],
        ),
        migrations.CreateModel(
            name='RentalBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Package', models.CharField(choices=[('STDR', 'Standard'), ('DELX', 'Deluxe'), ('PREM', 'Premium'), ('SPEC', 'Platinum')], default='Standard', max_length=10)),
                ('Location', models.CharField(default='N/A', max_length=50)),
                ('Target_Date', models.DateField()),
                ('Total', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('Completed', models.BooleanField(default=False)),
                ('Ord_TS', models.CharField(default='N/A', editable=False, max_length=25)),
                ('Flavor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RL_App.flavoring')),
                ('Rental_Request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='RL_App.itemorder')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('Review_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('Cust_Name', models.CharField(max_length=40)),
                ('Rating', models.IntegerField(choices=[('None', 0), ('Unsatisfied', 1), ('Poor', 2), ('Average', 3), ('Good', 4), ('Excellent', 5)], editable=False)),
                ('Details', models.TextField(editable=False)),
                ('RVW_TS', models.CharField(editable=False, max_length=25)),
                ('Cust_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RL_App.account')),
            ],
        ),
    ]
