# Generated by Django 5.0.1 on 2024-02-08 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('User_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('First_Name', models.CharField(max_length=40)),
                ('Last_Name', models.CharField(max_length=40)),
                ('Phone_Number', models.CharField(max_length=40)),
                ('Email', models.EmailField(max_length=30)),
                ('Password', models.CharField(max_length=15)),
                ('RL_Points', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('Product_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('Product_Type', models.CharField(choices=[('Flavor', 'FLAV'), ('Consumable', 'CNSM'), ('Asset', 'ASST'), ('Advertisement', 'ADVT'), ('Miscellaneous', 'MISC')], max_length=15)),
                ('Product_Name', models.CharField(max_length=25)),
                ('Product_Description', models.TextField(max_length=1000)),
                ('Price', models.DecimalField(decimal_places=2, default=0, max_digits=6, max_length=10)),
                ('Available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField(default=0)),
                ('Order_Items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RL_App.product')),
            ],
        ),
        migrations.CreateModel(
            name='RentalOrder',
            fields=[
                ('Rental_Num', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('Package', models.CharField(choices=[('STDR', 'Standard'), ('DELX', 'Deluxe'), ('PREM', 'Premium'), ('SPEC', 'Platinum')], default='N/A', max_length=10)),
                ('Location', models.CharField(default='N/A', max_length=50)),
                ('Target_Date', models.DateField()),
                ('Ord_TS', models.CharField(default='N/A', editable=False, max_length=25)),
                ('Completed', models.BooleanField(default=False)),
                ('Cus_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RL_App.account')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('Review_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('Cust_Name', models.CharField(max_length=40)),
                ('Rating', models.IntegerField(editable=False)),
                ('Details', models.TextField(editable=False)),
                ('RVW_TS', models.CharField(editable=False, max_length=25)),
                ('Cust_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RL_App.account')),
            ],
        ),
    ]
