# Generated by Django 5.0.1 on 2024-01-27 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RL_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('User_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('First_Name', models.CharField(max_length=40)),
                ('Last_Name', models.CharField(max_length=40)),
                ('Phone_Number', models.CharField(max_length=40)),
                ('Email', models.EmailField(max_length=30)),
                ('Password', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='rentalorder',
            old_name='Rent_Order',
            new_name='Rental_Number',
        ),
        migrations.AddField(
            model_name='rentalorder',
            name='Package',
            field=models.CharField(choices=[('STDR', 'Standard'), ('DELX', 'Deluxe'), ('PREM', 'Premium'), ('SPEC', 'Platinum')], default='N/A', max_length=10),
        ),
        migrations.AddField(
            model_name='rentalorder',
            name='Target_Date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='Price',
            field=models.FloatField(max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_Type',
            field=models.CharField(choices=[('Flavor', 'FLAV'), ('Consumable', 'CNSM'), ('Asset', 'ASST'), ('Advertisement', 'ADVT'), ('Miscellaneous', 'MISC')], max_length=15),
        ),
        migrations.AlterField(
            model_name='rentalorder',
            name='Completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rentalorder',
            name='Location',
            field=models.CharField(default='N/A', editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='rentalorder',
            name='Ord_TS',
            field=models.CharField(default='N/A', editable=False, max_length=25),
        ),
        migrations.AlterField(
            model_name='review',
            name='Details',
            field=models.TextField(editable=False),
        ),
        migrations.AlterField(
            model_name='review',
            name='RVW_TS',
            field=models.CharField(editable=False, max_length=25),
        ),
        migrations.AlterField(
            model_name='review',
            name='Rating',
            field=models.IntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='rentalorder',
            name='Cus_id',
            field=models.ForeignKey(default='N/A', editable=False, on_delete=django.db.models.deletion.CASCADE, to='RL_App.account'),
        ),
        migrations.AlterField(
            model_name='review',
            name='Cust_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RL_App.account'),
        ),
        migrations.DeleteModel(
            name='Accounts',
        ),
    ]
