# Generated by Django 5.0.1 on 2024-02-08 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RL_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='RL_Points',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
