# Generated by Django 5.0.1 on 2024-02-11 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RL_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flavoring',
            name='Image',
            field=models.ImageField(upload_to='RL_Styles/Graphics/RL_Images/'),
        ),
    ]
