# Generated by Django 5.0.1 on 2024-01-27 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RL_App', '0002_account_orderdetail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalorder',
            name='Target_Date',
            field=models.DateField(default='9999-12-31'),
        ),
    ]
