# Generated by Django 5.0.1 on 2024-01-27 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RL_App', '0005_alter_rentalorder_target_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalorder',
            name='Target_Date',
            field=models.DateField(),
        ),
    ]
