# Generated by Django 5.0.1 on 2024-01-27 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RL_App', '0006_alter_rentalorder_target_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, max_length=10),
        ),
    ]
